[package]
name = "toiletcli"
readme = "README.md"
authors = ["toiletbril"]
description = "Common functions for CLI applications."

license = "MIT"

version = "0.3.0"
edition = "2021"

include = ["/src"]
keywords = ["cli", "tools", "lib"]
categories = ["command-line-utilities"]

[features]
default = ["colors", "flags", "lines"]
colors = []
flags = []
lines = []
# Replaces all colors from 'color' module with mock strings for debugging.
mock_colors = []

[lib]
name = "toiletcli"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]
test = true

[[example]]
name = "cat"
path = "examples/cat.rs"

[[example]]
name = "colors"
path = "examples/colors.rs"

[[example]]
name = "flags"
path = "examples/flags.rs"

[[example]]
name = "lines"
path = "examples/lines.rs"

[profile.release]
opt-level = 3
strip = true
lto = true
