[package]
name = "toiletcli"
readme = "README.md"
authors = ["toiletbril"]
description = "Common functions for CLI applications."

license = "MIT"

version = "0.1.0"
edition = "2021"

include = ["/src"]
keywords = ["cli", "tools", "lib"]
categories = ["command-line-utilities"]

[lib]
name = "toiletcli"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]
test = true

[[example]]
name = "cat"
path = "examples/cat.rs"

[profile.release]
opt-level = 3
strip = true
lto = true
