[package]
name    = "toiletcli"
readme  = "README.md"
authors = ["toiletbril"]
license = "MIT"
version = "0.3.0"
edition = "2021"

description = "Common functions for CLI applications."

include    = ["/src"]
keywords   = ["cli", "tools", "lib"]
categories = ["command-line-utilities"]

[features]
default = ["flags", "ansi"]
ansi    = []
flags   = []
# Replaces all colors from 'color' module with mock strings for debugging.
mock_codes = []

[lib]
name = "toiletcli"
path = "src/lib.rs"
test = true
crate-type = ["cdylib", "lib"]

[[example]]
name = "cat"
path = "examples/cat.rs"

[[example]]
name = "colors"
path = "examples/colors.rs"

[[example]]
name = "flags"
path = "examples/flags.rs"

[[example]]
name = "lines"
path = "examples/lines.rs"

[profile.release]
opt-level = 3
strip = true
lto = true
